#
# CircleCI configuration for soon-fm
#

version: 2

jobs:
  setup:
    working_directory: ~/soon-fm
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: ~/soon-fm-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm i --no-progress
      - save_cache:
          key: ~/soon-fm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"

  test:
    working_directory: ~/soon-fm
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: ~/soon-fm-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm run lint
      - run: xvfb-run -a npm run test:ci
      - run: npm run coverage

  build:
    working_directory: ~/soon-fm
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: ~/soon-fm-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm run build -- --prod --progress false
      - save_cache:
          key: dist-{{ .Revision }}
          paths:
            - dist

  deploy:
    working_directory: ~/soon-fm
    machine: true
    environment:
      REPO: gcr.io/soon-fm-production/frontend
      TAG: $(sed 's/master/latest/;s/\//\-/' <<<$CIRCLE_BRANCH)
      PROJECT_NAME: soon-fm-production
      GCLOUD_COMPUTE_ZONE: europe-west1-c
    steps:
      - checkout
      - restore_cache:
          key: dist-{{ .Revision }}

      - run: echo $GCLOUD_SERVICE_AUTH | base64 --decode -i > ${HOME}/account-auth.json
      - run: sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
      - run: sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update kubectl
      - run: sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/account-auth.json
      - run: sudo /opt/google-cloud-sdk/bin/gcloud config set project ${PROJECT_NAME}
      - run: sudo /opt/google-cloud-sdk/bin/gcloud config set compute/zone ${GCLOUD_COMPUTE_ZONE}

      - run: docker build -t $REPO:$CIRCLE_SHA1 .
      - run: docker tag $REPO:$CIRCLE_SHA1 $REPO:latest
      - run: sudo /opt/google-cloud-sdk/bin/gcloud --quiet container clusters get-credentials production
      - run: sudo /opt/google-cloud-sdk/bin/gcloud --quiet config set container/cluster production
      - run: sudo /opt/google-cloud-sdk/bin/gcloud docker -- push $REPO:$CIRCLE_SHA1
      - run: sudo /opt/google-cloud-sdk/bin/gcloud docker -- push $REPO:latest
      - run: sudo chown -R $USER $HOME/.config
      - run: sudo chown -R $USER $HOME/.kube
      - run: cat k8s.yml | sed "s#\$TAG#${CIRCLE_SHA1}#g" | kubectl apply -f -

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
