# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2
jobs:
  build:
    working_directory: ~/fm-frontend
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install globals
          command: sudo npm install -q -g @angular/cli@latest
      - run:
          name: npm install
          command: sudo npm -q install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run build -- --prod

      - save_cache:
          key: dist-{{ .Revision }}
          paths:
            - dist
  deploy:
    working_directory: ~/fm-frontend
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: dist-{{ .Revision }}
      - run: docker build -t quay.io/thisissoon/fm-frontend:latest .

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
